SELECT CONCAT('Podium: ', team) AS NAME
FROM league
WHERE POSITION = 1 OR POSITION = 2 OR POSITION = 3
UNION ALL
SELECT CONCAT('Demoted: ', team) AS NAME
FROM league
WHERE POSITION = 14 OR POSITION = 15